### ISSUE TITLE
do a simple search on the tasks list

### ISSUE THREAD

**Issue by jasontanma** [cs2103jan2015-w14-4j/main#11]
So that he can find out the tasks he wanted to look at.

**Comment by comilao** [comment]
Loop through the whole cached ArrayList, compare one by one, then return an ArrayList of matched results.

**Comment by comilao** [comment]
Do we need to consider this situation? eg, the task is stored like "meet in school" with more info, the user typed search scholo, in this case, do we return this "meet in school" task? Or is it beyond a "simple" search? @jasontanma @LaonWeis @yhannq

**Comment by comilao** [comment]
["search", "things to search", (the rest all null) ]
