### ISSUE TITLE
implement warnings for clashed timing events

### ISSUE THREAD

**Issue by jasontanma** [cs2103jan2015-w14-4j/main#18]
So that he can reschedule those events.

**Comment by comilao** [comment]
This is a finding clashed schedule algorithm. Sort all the tasks according to their starting time, if the new task's endTime is between a task's duration, or one of the existing tasks' endTime is between the new tasks' duration, or they have exactly the same startTime and endTime, then there is a clash. @jasontanma @LaonWeis @yhannq

**Comment by comilao** [comment]
What should we do, if the user insist adding this clashing time event? I mean it is possible for events like this "go shopping 13:00 20:00" and "dinner with Eva 18:00 19:00".

**Comment by comilao** [comment]
ArrayList index 0 is the original one, the one after index 0 is all the clashed tasks

**Comment by comilao** [comment]
1.task from 2 to 4
2.add task 2 to 3(create a task successfully)
3.created
