### ISSUE TITLE
implement blocking multiple blocks of time

### ISSUE THREAD

**Issue by jasontanma** [cs2103jan2015-w14-4j/main#6]
So that he can reserve those slots for undecided events.

**Comment by comilao** [comment]
I am thinking creating a pseudo task with ID like 999 (any invalid ID less than 1000 will do), but this will create a problem for view task.
Or use another ArrayList to store a schedule object (with ID, name(maybe name it as "blocked" or something similar), start and end time). @jasontanma @LaonWeis @yhannq

**Comment by comilao** [comment]
block is same as add a task, reserve 1 priority for blocked tasks.

**Comment by comilao** [comment]
task name is "BLOCKED"
priority will be decided later
